name: veda_pages
publish_to: none

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  models:
    git:
      url: git@github.com:u4-d/veda_shared.git
      path: dart/models
      ref: main

  app_config:
    git:
      url: git@github.com:u4-d/veda_shared.git
      path: dart/app_config
      ref: main

  ranking:
    git:
      url: git@github.com:u4-d/veda_shared.git
      path: flutter/stock/ranking
      ref: main

  my_supabase_service:
    git:
      url: git@github.com:u4-d/veda_shared.git
      path: dart/my_supabase_service
      ref: main
